name: Build and publish

on:
    push:
        tags:
            - "*"

jobs:
    build:
        name: Build for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      artifact_name: IEC104_Slave
                    - os: windows-latest
                      artifact_name: IEC104_Slave.exe

        steps:
            - uses: actions/checkout@v2

            - name: Build for Linux
              if: matrix.os == 'ubuntu-latest'
              run: make

            - name: Build for Windows
              if: matrix.os == 'windows-latest'
              run: make

            - name: Upload binaries to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: Bin/${{ matrix.artifact_name }}
                  asset_name: ${{ matrix.asset_name }}
                  tag: ${{ github.ref }}
